{
 "title": "sender",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   { "name": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{instance=\"$instance\", job=\"$job\"}[1m]) / rate(http_server_requests_seconds_count{instance=\"$instance\", job=\"$job\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{instance=\"$instance\", job=\"$job\", uri!~\".*actuator.*\", status!~\"2.+\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{instance=\"$instance\", job=\"$job\", uri!~\".*actuator.*\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{instance=\"$instance\", job=\"$job\", uri!~\".*actuator.*\"}[5m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(system_cpu_usage) * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes) / 1024 / 1024 ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}